export const TatData = [
  
      {
        id: "s1",
        name: "Team Sync",
        date: "2025-05-20",
        totalCount: 3,
        videoCount: 2,
        nonVideoCount: 1,
        users: [
          {
            name: "Alice Johnson",
            email: "alice@example.com",
            dob: "1990-04-12",
            gender: "Female",
            mode: "video",
            paymentStatus: "completed",
            paymentType: "online",
          },
          {
            name: "Bob Smith",
            email: "bob@example.com",
            dob: "1987-09-20",
            gender: "Male",
            mode: "video",
            paymentStatus: "pending",
            paymentType: "offline",
          },
          {
            name: "Charlie Brown",
            email: "charlie@example.com",
            dob: "1992-02-15",
            gender: "Male",
            mode: "non-video",
            paymentStatus: "completed",
            paymentType: "offline",
          },
        ],
      },
      {
        id: "s2",
        name: "Product Planning",
        date: "2025-05-21",
        totalCount: 4,
        videoCount: 3,
        nonVideoCount: 1,
        users: [
          {
            name: "Dana White",
            email: "dana@example.com",
            dob: "1985-08-11",
            gender: "Female",
            mode: "video",
            paymentStatus: "completed",
            paymentType: "offline",
          },
          {
            name: "Ethan Stone",
            email: "ethan@example.com",
            dob: "1991-03-14",
            gender: "Male",
            mode: "video",
            paymentStatus: "completed",
            paymentType: "online",
          },
          {
            name: "Fiona Miles",
            email: "fiona@example.com",
            dob: "1994-06-24",
            gender: "Female",
            mode: "video",
            paymentStatus: "pending",
            paymentType: "online",
          },
          {
            name: "George Hill",
            email: "george@example.com",
            dob: "1989-12-02",
            gender: "Male",
            mode: "non-video",
            paymentStatus: "completed",
            paymentType: "offline",
          },
        ],
      },
      {
        id: "s3",
        name: "Quarterly Review",
        date: "2025-05-22",
        totalCount: 2,
        videoCount: 1,
        nonVideoCount: 1,
        users: [
          {
            name: "Hannah Lee",
            email: "hannah@example.com",
            dob: "1993-07-19",
            gender: "Female",
            mode: "video",
            paymentStatus: "completed",
            paymentType: "online",
          },
          {
            name: "Ian Wright",
            email: "ian@example.com",
            dob: "1986-11-05",
            gender: "Male",
            mode: "non-video",
            paymentStatus: "pending",
            paymentType: "offline",
          },
        ],
      },
      {
        id: "s4",
        name: "Customer Feedback",
        date: "2025-05-23",
        totalCount: 5,
        videoCount: 2,
        nonVideoCount: 3,
        users: [
          {
            name: "Jackie Chan",
            email: "jackie@example.com",
            dob: "1980-12-01",
            gender: "Male",
            mode: "video",
            paymentStatus: "completed",
            paymentType: "offline",
          },
          {
            name: "Karen Gillan",
            email: "karen@example.com",
            dob: "1990-05-14",
            gender: "Female",
            mode: "non-video",
            paymentStatus: "pending",
            paymentType: "online",
          },
          {
            name: "Liam Payne",
            email: "liam@example.com",
            dob: "1995-03-29",
            gender: "Male",
            mode: "video",
            paymentStatus: "completed",
            paymentType: "online",
          },
          {
            name: "Monica Bell",
            email: "monica@example.com",
            dob: "1988-01-17",
            gender: "Female",
            mode: "non-video",
            paymentStatus: "completed",
            paymentType: "offline",
          },
          {
            name: "Nathan Drake",
            email: "nathan@example.com",
            dob: "1982-10-10",
            gender: "Male",
            mode: "non-video",
            paymentStatus: "pending",
            paymentType: "online",
          },
        ],
      },
      {
        id: "s5",
        name: "Strategy Meetup",
        date: "2025-05-24",
        totalCount: 3,
        videoCount: 1,
        nonVideoCount: 2,
        users: [
          {
            name: "Olivia Green",
            email: "olivia@example.com",
            dob: "1996-09-03",
            gender: "Female",
            mode: "non-video",
            paymentStatus: "completed",
            paymentType: "online",
          },
          {
            name: "Peter Adams",
            email: "peter@example.com",
            dob: "1990-02-28",
            gender: "Male",
            mode: "non-video",
            paymentStatus: "pending",
            paymentType: "offline",
          },
          {
            name: "Quinn Rivers",
            email: "quinn@example.com",
            dob: "1985-07-07",
            gender: "Non-Binary",
            mode: "video",
            paymentStatus: "completed",
            paymentType: "online",
          },
        ],
      }
    ]