import React, { useState, useEffect } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import styles from "./index.module.scss";
import { Button } from "../../../common/components/Button";
import { ArrowLeft } from "lucide-react";
import { postCall, getCall, putCall } from "../../../services/apiService";
import { endPoints, PORTAL } from "../../../constants/urlConstants";
import { FORM_BUILDER_DEFAULTS, PUBLISH_MODAL_TEXT } from "../../../constants/textConstants";
import ImageUpload from "../../../components/ImageUpload";
import CustomDatePicker from "../../../common/components/CustomDatePicker";
import CustomTimePicker from "../../../common/components/CustomTimePicker";
import DropdownTextfield from "../../../common/components/DropdownTextfield";
import { FormProvider, get, useForm } from "react-hook-form";
// Generated by Copilot
import Stepper from "../../../components/programStepper";
import RectangularCard from "../../../components/RectangularCard";
import sprialIcon from "../../../assets/images/spiral-icon.svg"; // Generated by Copilot
import { getItemInLocalStorage } from "../../../services/localStorage";
import ProgramPreference from "../../../common/components/programPreference";
import { transformQuestionOptions } from "../../../utils/registrationUtils";
import PublishModal, { PublishData } from "../../../components/FormBuilderEdit/PublishModal";
import { safeCapitalize } from "../../../utils/commonFunctions";
import BannerRenderer from "../../../common/components/BannerRenderer";

interface FormSection {
  id: number;
  name: string;
  description: string;
  parentSectionId?: number | null;
  displayOrder?: number;
}

interface QuestionOption {
  id: number;
  option: {
    id: number;
    name: string;
    type: string;
  };
}

interface Question {
  id: number;
  label: string;
  type: string;
  config: {
    isRequired: boolean;
    minCharacter?: number;
    maxCharacters?: number;
    validationPattern?: string;
    endPoint?: string;
    questions?: any[]; // For multiQuestion type
  };
  formSection: FormSection;
  questionOptionMaps: QuestionOption[];
}

interface ProgramQuestionMap {
  id: number;
  question: Question;
  displayOrder: number;
}

// Update the GroupedQuestions interface
interface GroupedQuestions {
  sections: Array<{
    sectionId: number;
    sectionName: string;
    questions: ProgramQuestionMap[];
    sectionDisplayOrder: number;
    subSections?: Array<{
      subSectionId: number;
      subSectionName: string;
      questions: ProgramQuestionMap[];
      displayOrder: number;
    }>;
  }>;
}

interface ApiOption {
  value: string;
  label: string;
}

// Update the PublishPayload interface
interface PublishPayload {
  programId: number;
  sections: Array<{
    sectionName: string;
    questions: Array<{
      questionId: number;
      displayOrder: number;
    }>;
    sectionDisplayOrder: number;
  }>;
  registrationLevel: string;
  programSessionId: number;
}

// Add this interface for API response
interface ProgramQuestionResponse {
  data: {
    statusCode: number;
    data: any[];
  };
}

const PreviewForm: React.FC = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const [formData, setFormData] = useState<{ [key: string]: any }>({});
  // Update the state type
  const [groupedQuestions, setGroupedQuestions] = useState<GroupedQuestions>({
    sections: [],
  });
  const methods = useForm(); // Initialize methods for FormProvider
  const [apiOptions, setApiOptions] = useState<ApiOption[]>([]);
  const [apiOptionsMap, setApiOptionsMap] = useState<{
    [key: number]: ApiOption[];
  }>({});
  const userId = getItemInLocalStorage("seekerDetails").id || 0;

  const programName = location.state?.programName || "Program";
  const bannerImage = location.state?.bannerImage || "";
  const bannerImageUrl = location.state?.bannerImageUrl || null;
  const bannerAnimationUrl = location.state?.bannerAnimationUrl || null;
  const programId = location.state?.programId || 0;
  const columnLayout = location.state?.selectedForm || "2";
  const fromFormBuilder = location.state?.fromFormBuilder || false; // New flag to check navigation source
  const cardDetails = location.state?.cardDetails;

  // Publish modal states
  const [isPublishModalOpen, setIsPublishModalOpen] = useState(false);
  const [isPublishing, setIsPublishing] = useState(false);
  const [programStatus, setProgramStatus] = useState<string | null>(null);
  const [programAccessUserIds, setProgramAccessUserIds] = useState<number[]>([]); // New state to track selected user IDs for program access


  const [availablePrograms, setAvailablePrograms] = useState<any[]>([]);


  // Add new state for program questions
  const [programQuestions, setProgramQuestions] = useState<
    ProgramQuestionMap[]
  >([]);

  // Modify the fetchProgramQuestions function
  const fetchProgramQuestions = async () => {
    try {
      if (!programId) return;
      const response = await getCall(`${endPoints?.program}/${programId}`, undefined, PORTAL);

      // Extract program status
      setProgramStatus(response?.data?.data?.status || null);
      setProgramAccessUserIds(response?.data?.data?.programAccessUserIds || []);
      // Extract sub-programs/sessions for draganddrop (preference) questions
      const fetchedProgramData = response?.data?.data;
      const sessions = fetchedProgramData?.groupedPrograms?.length
        ? fetchedProgramData.groupedPrograms
        : fetchedProgramData?.programSessions?.length
        ? fetchedProgramData.programSessions
        : [];
      setAvailablePrograms(sessions);
      if (
        response?.data?.statusCode === 200 &&
        response.data.data?.programQuestionMaps?.length > 0
      ) {
        const transformedQuestions = response.data.data.programQuestionMaps.map(
          (item: any) => {
            // Transform question options to handle new optionConfig format
            const transformedQuestion = transformQuestionOptions(item.question);
            return {
              id: item.id,
              question: {
                id: transformedQuestion.id,
                label: transformedQuestion.label,
                type: transformedQuestion.type,
                config: transformedQuestion.config || {
                  isRequired: false,
                  minCharacter: null,
                  maxCharacters: null,
                  validationPattern: null,
                  endPoint: null,
                },
                formSection: {
                  id: item?.programQuestionFormSection?.id || 1,
                  name:
                    item.programQuestionFormSection?.name ||
                    FORM_BUILDER_DEFAULTS.SECTION_NAME,
                  description:
                    item.programQuestionFormSection?.description ||
                    FORM_BUILDER_DEFAULTS.SECTION_DESCRIPTION,
                  parentSectionId:
                    item?.programQuestionFormSection?.parentSectionId || null,
                  displayOrder:
                    item?.programQuestionFormSection?.displayOrder || 0,
                },
                questionOptionMaps: transformedQuestion.questionOptionMaps || [],
                answerLocation: transformedQuestion.answerLocation || "",
                bindingKey: transformedQuestion.bindingKey || "",
              },
              displayOrder: item.displayOrder || 0,
              registrationLevel: item.registrationLevel || FORM_BUILDER_DEFAULTS.PROGRAM,
            };
          },
        );

        setProgramQuestions(transformedQuestions);
      } else {
        // No data from API - set empty array
        setProgramQuestions([]);
      }
    } catch (error) {
      console.error("Error fetching program questions:", error);
      setProgramQuestions([]);
    }
  };

  useEffect(() => {
    fetchProgramQuestions();
  }, [programId]);

  // Update the grouping useEffect to use programQuestions instead of programQuestionMaps
  useEffect(() => {
    if (!programQuestions.length) return;

    // Separate parent sections and subsections
    const parentSectionsMap: { [key: number]: any } = {};
    const subSectionsMap: { [key: number]: any } = {};

    programQuestions.forEach((questionMap) => {
      const sectionId = questionMap.question.formSection.id;
      const parentSectionId = questionMap.question.formSection.parentSectionId;
      const sectionDisplayOrder = questionMap.question.formSection.displayOrder || 0;

      if (parentSectionId) {
        // This is a subsection
        if (!subSectionsMap[sectionId]) {
          subSectionsMap[sectionId] = {
            subSectionId: sectionId,
            subSectionName: questionMap.question.formSection.name,
            questions: [],
            displayOrder: sectionDisplayOrder,
            parentSectionId: parentSectionId,
          };
        }
        subSectionsMap[sectionId].questions.push(questionMap);
      } else {
        // This is a parent section
        if (!parentSectionsMap[sectionId]) {
          parentSectionsMap[sectionId] = {
            sectionId: sectionId,
            sectionName: questionMap.question.formSection.name,
            questions: [],
            sectionDisplayOrder: sectionDisplayOrder,
            subSections: [],
          };
        }
        parentSectionsMap[sectionId].questions.push(questionMap);
      }
    });

    // Attach subsections to their parent sections
    Object.values(subSectionsMap).forEach((subSection: any) => {
      const parentSection = parentSectionsMap[subSection.parentSectionId];
      if (parentSection) {
        parentSection.subSections.push(subSection);
      }
    });

    // Convert to array
    const sectionsArray = Object.values(parentSectionsMap);

    // Sort questions within each section and subsection by display order
    sectionsArray.forEach((section: any) => {
      section.questions.sort((a: any, b: any) => a.displayOrder - b.displayOrder);
      if (section.subSections) {
        section.subSections.sort((a: any, b: any) => a.displayOrder - b.displayOrder);
        section.subSections.forEach((subSection: any) => {
          subSection.questions.sort((a: any, b: any) => a.displayOrder - b.displayOrder);
        });
      }
    });

    // Sort sections by their display order
    sectionsArray.sort((a: any, b: any) => a.sectionDisplayOrder - b.sectionDisplayOrder);

    setGroupedQuestions({ sections: sectionsArray });
  }, [programQuestions]);

  useEffect(() => {
    const fetchOptionsForQuestions = async () => {
      // Loop through sections array
      for (const section of groupedQuestions.sections) {
        // Loop through questions in each section
        for (const questionMap of section.questions) {
          const { id, type, config } = questionMap.question;
          if (type === "apicall" && config.endPoint && !apiOptionsMap[id]) {
            try {
              const response = await getCall(
                config.endPoint,
                undefined,
                PORTAL,
              );
            
              if (
                response?.data?.statusCode === 200 &&
                Array.isArray(response.data.data)
              ) {
                const options = response.data.data.map((item: any) => ({
                  value: item.id.toString(),
                  label: item.name,
                }));
                setApiOptionsMap((prev) => ({
                  ...prev,
                  [id]: options,
                }));
              }
            } catch (error) {
              console.error(
                `Error fetching options for question ${id}:`,
                error,
              );
            }
          }
        }
      }
    };

    fetchOptionsForQuestions();
  }, [groupedQuestions]);

  const handleInputChange = (questionId: number, value: any) => {
    setFormData((prev) => ({
      ...prev,
      [questionId]: value,
    }));
  };


  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    // Only submit if coming from form builder
    if (!fromFormBuilder) {
      return;
    }

    // Prepare the payload in the desired format
    const payload = {
      programId: programId,
      questions: [],
      registrationLevel: "program",
      programSessionId: null,
      customQuestions: [],
    };

    // Get all existing question IDs and find the max to continue sequence
    const allQuestions = [];
    Object.entries(groupedQuestions).forEach(
      ([sectionId, { section, questions }]) => {
        questions.forEach((questionMap) => {
          allQuestions.push({
            questionMap,
            section,
          });
        });
      },
    );

    // Sort by display order to maintain sequence
    allQuestions.sort(
      (a, b) => a.questionMap.displayOrder - b.questionMap.displayOrder,
    );

    let displayOrder = 0;

    // Process questions
    allQuestions.forEach((item) => {
      const { questionMap, section } = item;
      const question = questionMap.question;

      // Only include questions that exist in the system (ID <= 362 or confirmed existing questions)
      // Exclude timestamp-based IDs or newly created questions that don't exist in DB
      if (
        question.id <= 362 ||
        (question.id < 1000000000000 && question.id > 362)
      ) {
        // This is an existing published question
        payload.questions.push({
          questionId: question.id,
          displayOrder: displayOrder++,
        });
      }

      // Check if this is a custom question that should be included
      if (
        question.type === "select" ||
        question.type === "draganddrop" ||
        question.label === "City" ||
        question.label === "preferences" ||
        question.label === "ID Type" ||
        question.label === "T-Shirt Size" ||
        question.id >= 1000000000000
      ) {
        // Include timestamp-based IDs as custom questions

        const customQuestion = {
          question: {
            label: question.label,
            type: question.type,
            section: section.id || 1,
            config: {
              maxValue: question.config.maxValue || null,
              minValue: question.config.minValue || null,
              dependsOn: question.config.dependsOn || [],
              isRequired: question.config.isRequired,
              minCharacter: question.config.minCharacter || null,
              maxCharacters: question.config.maxCharacters || null,
              conditionalFields: question.config.conditionalFields || [],
              validationPattern: question.config.validationPattern || null,
            },
          },
          options: question.questionOptionMaps.map((optionMap) => ({
            name: optionMap.option.name,
            type: optionMap.option.type || "string",
            category: null,
          })),
          displayOrder: payload.customQuestions.length + 6,
        };

        payload.customQuestions.push(customQuestion);
      }
    });


    try {
      const response = await postCall(endPoints?.programQuestion, payload, PORTAL);

      if (response?.data?.statusCode === 201) {
        navigate("/admin/action-cards");
      } else {
        throw new Error("Failed to submit form");
      }
    } catch (error) {
      console.error("Error during form submission:", error);
    }
  };

  // Update the handlePublish function
  const handlePublish = async (publishData: PublishData) => {
    try {
      setIsPublishing(true);
      
      if (!programId) {
        console.error("No program ID found");
        alert("Unable to publish: Program ID not found");
        return;
      }

      const publishResponse = await putCall(
        endPoints.updateProgramStatus(programId),
        publishData,
        PORTAL
      );

      if (publishResponse?.data?.statusCode === 200 || publishResponse?.data?.statusCode === 201) {
        alert(`Program published successfully as ${publishData.accessType}!`);
        setIsPublishModalOpen(false);
        
        // Navigate back to action cards or program list
        navigate("/admin/action-cards");
      } else {
        throw new Error("Failed to publish program");
      }
    } catch (error) {
      console.error("Error publishing program:", error);
      alert("Failed to publish program. Please try again.");
    } finally {
      setIsPublishing(false);
    }
  };

  const handleBack = () => {
    navigate(`/admin/add-program/${programId}`, {
      state: { programId },
    });
  };

  const handleBackToPrograms = () => {
    navigate("/admin/action-cards");
  };

  const fetchApiOptions = async (endPoint: string) => {
    try {
      const response = await getCall(endPoint);
      if (response?.data?.statusCode === 200) {
        const options = response.data.data.map((item: any) => ({
          value: item.id.toString(),
          label: item.name,
        }));
        setApiOptions(options);
      }
    } catch (error) {
      console.error("Error fetching options:", error);
    }
  };

  const renderInput = (question: Question) => {
    const { id, label, type, config, questionOptionMaps } = question;
    const value = formData[id] || "";

    switch (type) {
      case "text":
      case "email":
        return (
          <input
            type={type}
            id={`question-${id}`}
            value={value}
            onChange={(e) => handleInputChange(id, e.target.value)}
            className={styles.input}
          />
        );

      case "textarea":
        return (
          <textarea
            id={`question-${id}`}
            value={value}
            onChange={(e) => handleInputChange(id, e.target.value)}
            className={styles.textarea}
            rows={4}
          />
        );

      case "date":
        return (
          <CustomDatePicker
            value={value ? new Date(value) : undefined}
            onChange={(date) => handleInputChange(id, date?.toISOString())}
            futureDate={true}
            errorExist={false}
            dataTestId={`question-${id}`}
            readOnly={false}
            styleChange={true}
          />
        );

      case "time":
        return (
          <CustomTimePicker
            value={value ? new Date(`1970-01-01T${value}`) : new Date()}
            onChange={(date) => {
              if (date) {
                const timeString = date.toLocaleTimeString("en-US", {
                  hour12: false,
                  hour: "2-digit",
                  minute: "2-digit",
                  second: "2-digit",
                });
                handleInputChange(id, timeString);
              }
            }}
            errorExist={false}
            dataTestid={`question-${id}`}
            readOnly={false}
            diffStyle={true}
          />
        );

      case "radio":
        return (
          <div className={styles.radioGroup}>
            {questionOptionMaps.map((optionMap) => (
              <label key={optionMap.id} className={styles.radioLabel}>
                <input
                  type="radio"
                  name={`question-${id}`}
                  value={optionMap.option.name}
                  checked={value === optionMap.option.name}
                  onChange={(e) => handleInputChange(id, e.target.value)}
                  className={styles.radioInput}
                />
                <span className={styles.radioText}>
                  {safeCapitalize(optionMap.option?.name)}
                </span>
              </label>
            ))}
          </div>
        );

      case "select":
        return (
          <FormProvider {...methods}>
            <DropdownTextfield
              name={`question-${id}`}
              label="" // Label is already rendered by parent
              options={questionOptionMaps.map((optionMap) => ({
                value: optionMap.option.name,
                label: safeCapitalize(optionMap.option?.name),
              }))}
              placeholder={`Select ${label.toLowerCase()}`}
              value={value}
              onValueChange={(selectedValue) =>
                handleInputChange(id, selectedValue)
              }
              error={undefined}
              width="100%"
              className={styles.customDropdown}
            />
          </FormProvider>
        );

      case "checkbox":
        return (
          <div className={styles.checkboxGroup}>
            {questionOptionMaps.map((optionMap) => (
              <label key={optionMap.id} className={styles.checkboxLabel}>
                <input
                  type="checkbox"
                  value={optionMap.option.name}
                  checked={
                    Array.isArray(value)
                      ? value.includes(optionMap.option.name)
                      : false
                  }
                  onChange={(e) => {
                    const currentValues = Array.isArray(value) ? value : [];
                    if (e.target.checked) {
                      handleInputChange(id, [...currentValues, e.target.value]);
                    } else {
                      handleInputChange(
                        id,
                        currentValues.filter((v) => v !== e.target.value),
                      );
                    }
                  }}
                  className={styles.checkboxInput}
                />
                <span className={styles.checkboxText}>
                  {safeCapitalize(optionMap.option?.name)}
                </span>
              </label>
            ))}
          </div>
        );

      case "file":
        return (
          <ImageUpload
            imageData={{
              dataUrl: value?.dataUrl || null,
              name: value?.name || null,
            }}
            onImageChange={(newImage: any) => handleInputChange(id, newImage)}
            placeholderText={`Upload ${label}`}
            accept="image/*, application/pdf"
            getImageUrl={(url: string) => {
              // Handle uploaded file URL if needed
            }}
            uniqueId={`question-${id}`}
          />
        );

      case "draganddrop": {
        const mahatriaChoiceProgram = {
          id: "mahatria_choice",
          name: "Mahatria Choice",
          duration: "",
          dates: "",
        };
        return (
          <ProgramPreference
            availablePrograms={availablePrograms}
            maxPreferences={availablePrograms?.length}
            onPreferencesChange={(pref) =>
              handleInputChange(
                id,
                pref != null ? encodeURIComponent(JSON.stringify(pref)) : null,
              )
            }
            question={question}
            mahatriaChoice={mahatriaChoiceProgram}
            value={value !== "" && value != null ? JSON.parse(decodeURIComponent(value)) : null}
          />
        );
      }

      case "apicall":
        return (
          <FormProvider {...methods}>
            <DropdownTextfield
              name={`question-${id}`}
              label=""
              options={apiOptionsMap[id] || []}
              placeholder={`Select ${label.toLowerCase()}`}
              value={value}
              onValueChange={(selectedValue) =>
                handleInputChange(id, selectedValue)
              }
              error={undefined}
              width="100%"
              className={styles.customDropdown}
            />
          </FormProvider>
        );

      case "multiQuestion": {
        const subQuestions = config.questions || [];
        const multiQuestionValue = formData[id] || {};
        
        return (
          <div className={styles.multiQuestionContainer}>
            {subQuestions.map((subQuestion: any, index: number) => {
              const subValue = multiQuestionValue[subQuestion.key] || "";
              const subFieldType = subQuestion.displayLabelType || "text";
              const charCount = subQuestion.maxCharacters 
                ? subQuestion.maxCharacters - (subValue?.length || 0)
                : null;
              
              return (
                <div key={subQuestion.key || index} className={styles.subQuestionField}>
                  {subQuestion.label && (
                    <label className={styles.subQuestionLabel}>
                      {subQuestion.label}
                    </label>
                  )}
                  
                  {subFieldType === "textarea" && (
                    <>
                      <textarea
                        value={subValue}
                        onChange={(e) => {
                          const newMultiValue = {
                            ...multiQuestionValue,
                            [subQuestion.key]: e.target.value
                          };
                          handleInputChange(id, newMultiValue);
                        }}
                        placeholder={subQuestion.placeholder || ""}
                        className={styles.textarea}
                        rows={4}
                      />
                      {charCount !== null && (
                        <div className={styles.charCount}>
                          {charCount} characters left
                        </div>
                      )}
                    </>
                  )}
                  
                  {(subFieldType === "text" || subFieldType === "email") && (
                    <>
                      <input
                        type={subFieldType}
                        value={subValue}
                        onChange={(e) => {
                          const newMultiValue = {
                            ...multiQuestionValue,
                            [subQuestion.key]: e.target.value
                          };
                          handleInputChange(id, newMultiValue);
                        }}
                        placeholder={subQuestion.placeholder || ""}
                        className={styles.input}
                      />
                      {charCount !== null && (
                        <div className={styles.charCount}>
                          {charCount} characters left
                        </div>
                      )}
                    </>
                  )}
                  
                  {subFieldType === "number" && (
                    <input
                      type="number"
                      value={subValue}
                      onChange={(e) => {
                        const newMultiValue = {
                          ...multiQuestionValue,
                          [subQuestion.key]: e.target.value
                        };
                        handleInputChange(id, newMultiValue);
                      }}
                      placeholder={subQuestion.placeholder || ""}
                      className={styles.input}
                      min={subQuestion.minValue}
                      max={subQuestion.maxValue}
                    />
                  )}
                  
                  {subFieldType === "slider" && (
                    <div className={styles.sliderContainer}>
                      <input
                        type="range"
                        value={subValue || subQuestion.minValue || 0}
                        onChange={(e) => {
                          const newMultiValue = {
                            ...multiQuestionValue,
                            [subQuestion.key]: e.target.value
                          };
                          handleInputChange(id, newMultiValue);
                        }}
                        min={subQuestion.minValue || 0}
                        max={subQuestion.maxValue || 100}
                        className={styles.slider}
                      />
                      <div className={styles.sliderValue}>
                        {subValue || subQuestion.minValue || 0}
                      </div>
                    </div>
                  )}
                  
                  {subFieldType === "radio" && subQuestion.options && (
                    <div className={styles.radioGroup}>
                      {subQuestion.options.map(
                        (option: string, optIndex: number) => (
                          <label key={optIndex} className={styles.radioLabel}>
                            <input
                              type="radio"
                              name={`${id}-${subQuestion.key}`}
                              value={option}
                              checked={subValue === option}
                              onChange={(e) => {
                                const newMultiValue = {
                                  ...multiQuestionValue,
                                  [subQuestion.key]: e.target.value,
                                };
                                handleInputChange(id, newMultiValue);
                              }}
                              className={styles.radioInput}
                            />
                            <span className={styles.radioText}>
                              {safeCapitalize(option)}
                            </span>
                          </label>
                        ),
                      )}
                    </div>
                  )}

                  {subFieldType === "checkbox" && subQuestion.options && (
                    <div className={styles.checkboxGroup}>
                      {subQuestion.options.map(
                        (option: string, optIndex: number) => (
                          <label
                            key={optIndex}
                            className={styles.checkboxLabel}
                          >
                            <input
                              type="checkbox"
                              value={option}
                              checked={
                                Array.isArray(subValue)
                                  ? subValue.includes(option)
                                  : false
                              }
                              onChange={(e) => {
                                const currentValues = Array.isArray(subValue)
                                  ? subValue
                                  : [];
                                const newSubValue = e.target.checked
                                  ? [...currentValues, option]
                                  : currentValues.filter((v) => v !== option);
                                const newMultiValue = {
                                  ...multiQuestionValue,
                                  [subQuestion.key]: newSubValue,
                                };
                                handleInputChange(id, newMultiValue);
                              }}
                              className={styles.checkboxInput}
                            />
                            <span className={styles.checkboxText}>
                              {safeCapitalize(option)}
                            </span>
                          </label>
                        ),
                      )}
                    </div>
                  )}
                  
                  {subFieldType === "select" && subQuestion.options && (
                    <FormProvider {...methods}>
                      <DropdownTextfield
                        name={`${id}-${subQuestion.key}`}
                        label=""
                        options={subQuestion.options.map((opt: string) => ({
                          value: opt,
                          label: safeCapitalize(opt),
                        }))}
                        placeholder={subQuestion.placeholder || "Select option"}
                        value={subValue}
                        onValueChange={(selectedValue) => {
                          const newMultiValue = {
                            ...multiQuestionValue,
                            [subQuestion.key]: selectedValue
                          };
                          handleInputChange(id, newMultiValue);
                        }}
                        error={undefined}
                        width="100%"
                        className={styles.customDropdown}
                      />
                    </FormProvider>
                  )}
                  
                  {subFieldType === "file" && (
                    <ImageUpload
                      imageData={{
                        dataUrl: subValue?.dataUrl || null,
                        name: subValue?.name || null,
                      }}
                      onImageChange={(newImage: any) => {
                        const newMultiValue = {
                          ...multiQuestionValue,
                          [subQuestion.key]: newImage
                        };
                        handleInputChange(id, newMultiValue);
                      }}
                      placeholderText={subQuestion.placeholder || "Upload file"}
                      accept="image/*, application/pdf"
                      getImageUrl={(url: string) => {}}
                      uniqueId={`${id}-${subQuestion.key}`}
                    />
                  )}
                </div>
              );
            })}
          </div>
        );
      }

      default:
        return (
          <input
            type="text"
            id={`question-${id}`}
            value={value}
            onChange={(e) => handleInputChange(id, e.target.value)}
            className={styles.input}
          />
        );
    }
  };

  if (programQuestions.length === 0 && groupedQuestions.sections.length === 0) {
    return (
      <div className={styles.container}>
        <div className={styles.noData}>
          <h2>No form data available</h2>
          <button onClick={handleBack} className={styles.backButton}>
            Go Back
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className={styles.container}>
      <div className={styles.programHeader}>
        <div className={styles.programHeaderText}>
          <ArrowLeft
            size={24}
            onClick={handleBack}
            className={styles.arrowIcon}
          />
          Create program
        </div>
      </div>
      <div>
        <Stepper currentStep={3} />
      </div>
      <p className={styles.heading}>
        Here's how your registration form will appears to Seekers.
      </p>
      <div className={styles.programImageForm}>
        <div className={styles.programBanner}>
          <div className={styles.calendarEffect}>
            <div className={styles.calendarEffectImg}>
              <img src={sprialIcon} />
            </div>
            <div className={styles.calendarEffectImg}>
              <img src={sprialIcon} />
            </div>
            <div className={styles.calendarEffectImg}>
              <img src={sprialIcon} />
            </div>
            <div className={styles.calendarEffectImg}>
              <img src={sprialIcon} />
            </div>
            <div className={styles.calendarEffectImg}>
              <img src={sprialIcon} />
            </div>
          </div>

          <BannerRenderer
            bannerAnimationUrl={bannerAnimationUrl}
            bannerImageUrl={bannerImageUrl}
            fallbackImage={bannerImage}
            alt="Program Banner"
            className={styles.bannerImage}
          />
        </div>

        <form onSubmit={handleSubmit}>
          <div className={styles.formContainer}>
            <div className={styles.form}>
              {groupedQuestions.sections.map((section) => {
                // Merge parent questions and subsections, then sort by displayOrder
                const mergedItems: Array<{
                  type: "question" | "subsection";
                  displayOrder: number;
                  data: any;
                }> = [];

                // Add parent questions
                section.questions.forEach((questionMap: any) => {
                  mergedItems.push({
                    type: "question",
                    displayOrder: questionMap.displayOrder,
                    data: questionMap,
                  });
                });

                // Add subsections - use the minimum question displayOrder within the subsection
                if (section.subSections) {
                  section.subSections.forEach((subSection: any) => {
                    // Find the minimum displayOrder of questions in this subsection
                    const minQuestionOrder =
                      subSection.questions.length > 0
                        ? Math.min(
                            ...subSection.questions.map(
                              (q: any) => q.displayOrder,
                            ),
                          )
                        : subSection.displayOrder;

                    mergedItems.push({
                      type: "subsection",
                      displayOrder: minQuestionOrder,
                      data: subSection,
                    });
                  });
                }

                // Sort by displayOrder
                mergedItems.sort((a, b) => a.displayOrder - b.displayOrder);

                return (
                  <div key={section.sectionId} className={styles.section}>
                    <div className={styles.sectionHeader}>
                      <h2 className={styles.sectionTitle}>
                        {section.sectionName}
                      </h2>
                    </div>

                    {/* Render items in displayOrder */}
                    {(() => {
                      const elements: JSX.Element[] = [];
                      let currentGridQuestions: any[] = [];

                      const flushGrid = () => {
                        if (currentGridQuestions.length > 0) {
                          elements.push(
                            <div
                              key={`grid-${elements.length}`}
                              className={`${styles.questionsGrid} ${columnLayout === "2" ? styles.twoColumn : styles.oneColumn}`}
                            >
                              {currentGridQuestions.map((questionMap) => (
                                <div
                                  key={questionMap.question.id}
                                  className={styles.questionContainer}
                                  data-question-type={questionMap.question.type}
                                >
                                  <label
                                    htmlFor={`question-${questionMap.question.id}`}
                                    className={styles.label}
                                  >
                                    {questionMap.question.label}
                                  </label>
                                  {renderInput(questionMap.question)}
                                </div>
                              ))}
                            </div>,
                          );
                          currentGridQuestions = [];
                        }
                      };

                      mergedItems.forEach((item) => {
                        if (item.type === "question") {
                          currentGridQuestions.push(item.data);
                        } else if (item.type === "subsection") {
                          flushGrid();
                          elements.push(
                            <div
                              key={`subsection-${item.data.subSectionId}`}
                              className={styles.subSectionsContainer}
                            >
                              <div className={styles.subSection}>
                                <div className={styles.subSectionHeader}>
                                  <h3 className={styles.subSectionTitle}>
                                    {item.data.subSectionName}
                                  </h3>
                                </div>
                                <div
                                  className={`${styles.questionsGrid} ${columnLayout === "2" ? styles.twoColumn : styles.oneColumn}`}
                                >
                                  {item.data.questions.map(
                                    (questionMap: any) => (
                                      <div
                                        key={questionMap.question.id}
                                        className={styles.questionContainer}
                                        data-question-type={
                                          questionMap.question.type
                                        }
                                      >
                                        <label
                                          htmlFor={`question-${questionMap.question.id}`}
                                          className={styles.label}
                                        >
                                          {questionMap.question.label}
                                        </label>
                                        {renderInput(questionMap.question)}
                                      </div>
                                    ),
                                  )}
                                </div>
                              </div>
                            </div>,
                          );
                        }
                      });

                      flushGrid();
                      return elements;
                    })()}
                  </div>
                );
              })}
            </div>

            {cardDetails && (
              <RectangularCard
                title={cardDetails.title}
                venue={cardDetails.venue}
                startDate={cardDetails.startDate}
                endDate={cardDetails.endDate}
                payment={cardDetails.payment}
              />
            )}
          </div>
          <div className={styles.divWithButtons}>
            <div className={styles.formRowButton}>
              <Button
                onClick={() => navigate("/admin/action-cards")}
                buttonClassName={styles.buttonContainerSecondary}
                buttonTextClassName={styles.buttonTextSecondary}
              >
                cancel
              </Button>
              <Button
                onClick={() => navigate(-1)}
                buttonClassName={styles.buttonContainerSecondary}
                buttonTextClassName={styles.buttonTextSecondary}
              >
                previous
              </Button>
              <Button
                onClick={() => setIsPublishModalOpen(true)}
                buttonClassName={styles.buttonContainerPrimary}
                buttonTextClassName={styles.buttonTextPrimary}
                disable={isPublishing}
              >
                {isPublishing ? "publishing..." : "publish"}
              </Button>
            </div>
          </div>
        </form>
      </div>

      {/* Publish Modal */}
      <PublishModal
        open={isPublishModalOpen}
        onClose={() => setIsPublishModalOpen(false)}
        onPublish={handlePublish}
        programId={programId || ""}
        isInternalPublish={false}
        programAccessUserIds={programAccessUserIds || []}
      />
    </div>
  );
};

export default PreviewForm;
