import { WARNING_MESSAGES } from "../../constants";
import { textConstant } from "../../constants/textConstants";
import { endPoints, PORTAL } from "../../constants/urlConstants";
import { deleteCallWithLoader, postCallWithLoader, putCallWithLoader } from "../../services/apiService";

interface User {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [x: string]: any;
  id: string;
  name: string;
  age: number;
  city: string;
  profile: string | null;
  gender: string;
}

interface Room {
  floor: string;
  roomId: string;
  capacity: number;
  occupants: { id: string; value: User | null }[];
  isChecked: boolean;
  remainingOccupancy: number;
}

export const pairYetToAssignSeekers = (
  seekers: unknown,
  setCheckReload: React.Dispatch<React.SetStateAction<boolean>>,
  setSkipRoom?: React.Dispatch<React.SetStateAction<boolean>>,
  setSelectedSeekers?: React.Dispatch<React.SetStateAction<User[]>>,
  programId?: string | number,
  subProgramId?: string | number,
  onClose?: () => void,
  setToastState?: (state: { open: boolean; message: string }) => void,
) => {
  const userIds = seekers?.map((item) => Number(item?.id));
  setSkipRoom && setSkipRoom(true);

  const payload = {
    programId: Number(programId),
    subProgramId: subProgramId,
    registrationIds: userIds,
    remarks: "",
    // pairCreatedBy: getItemInLocalStorage("userId") || 1,
  };

  postCallWithLoader(endPoints.createPair, payload, PORTAL,  textConstant.LARGE  )
    .then((response) => {
      if(response.data.statusCode === 201){  
        onClose && onClose();
        setCheckReload(true);
        if(setSelectedSeekers){
        setSelectedSeekers([]);
        }
      }
      else if( response?.data?.statusCode  >= 400 && response?.data?.statusCode < 500)
      {
        setToastState &&  setToastState({
          open: true,
          message: WARNING_MESSAGES.PAIR_FAIL_TEXT,
        });
      }
      else{
        setToastState &&  setToastState({
          open: true,
          message: WARNING_MESSAGES.SOMETHING_WENT_WRONG_TEXT,
        });
      }
    })
    .catch((error) => {
      console.error("Error pairing seekers", error);
    })
};

export const unpairYetToAssignSeekers = (
  seekerIds: number | string ,
  setCheckReload: React.Dispatch<React.SetStateAction<boolean>>,
  setSelectedSeekers: React.Dispatch<React.SetStateAction<unknown[]>>,
  setSkipRoom?: React.Dispatch<React.SetStateAction<boolean>>,
) => {
  deleteCallWithLoader(endPoints.deletePair(seekerIds), undefined, PORTAL, textConstant.LARGE )
    .then((response) => {
      console.log("Paired successfully", response);
    })
    .catch((error) => {
      console.error("Error pairing seekers", error);
    })
    .finally(() => {
      // Generated by Copilot - Set skipRoom to true before triggering reload
      setSkipRoom && setSkipRoom(true);
      setCheckReload(true);
      setSelectedSeekers([]);


    });
};

export const checkRoomisOccupied = (
  rooms: Array<Room>,
  occupantRoomId: string | null,
) => {
    const roomInventoryId = occupantRoomId?.split('-')[0];
    const room = rooms?.find((item) => item?.roomInventoryId?.toString() === roomInventoryId);
  return [
    room?.roomInventoryId,
    room?.occupants?.some((item) => item?.value !== null),
  ];
};

export const handleRoomAllocateForPair = (
  programRegistrationIds: Array<number>,
  roomInventoryId: number,
  programId?: string | number,
  subProgramId?: string | number | undefined,
  fetchRoomData?: (reload: boolean) => void,
  fetchApi?: (reload: boolean) => void,
  roomOffset?: number,
  setRoomOffset?: React.Dispatch<React.SetStateAction<number>>,
  offsetNumber?: number,
  userOffsetNumber?: number,
  seekerOffset?: number,
  setSeekerOffset?: React.Dispatch<React.SetStateAction<number>>,
) => {

  const payload = {
    programId: Number(programId),
    subProgramId:subProgramId,
    registrations: [
      {
        registrationId: programRegistrationIds[0],
        bedPosition: 1,
      },
      {
        registrationId: programRegistrationIds[1],
        bedPosition: 2,
      }
    ],
    roomInventoryId: roomInventoryId,
  };


  postCallWithLoader(endPoints?.roomAllocation, payload, PORTAL, textConstant.LARGE )
    .then((response) => {
      console.log("Room allocated successfully", response);
      // Other success actions can be added here if needed
    })
    .catch((error) => {
      console.error("Error allocating room", error);
    })
    .finally(() => {
      if(offsetNumber === roomOffset){
        fetchRoomData && fetchRoomData(true);
      }
      else{
        setRoomOffset && setRoomOffset(offsetNumber || 0);
      }
      if(userOffsetNumber === seekerOffset){
        fetchApi && fetchApi(true);
      }
      else{
        setSeekerOffset && setSeekerOffset(userOffsetNumber || 0);
      }
    });
};

export const editRoomAllocationForPair = (
  programRegistrationIds: Array<number>,
  roomInventoryId: number,
  programId?: string | number,
  subProgramId?: string | number | undefined,
  fetchRoomData?: (reload: boolean) => void,
  fetchApi?: (reload: boolean) => void,
  roomOffset?: number,
  setRoomOffset?: React.Dispatch<React.SetStateAction<number>>,
  offsetNumber?: number,
) => {
  const payload = {
    programId: Number(programId),
    subProgramId:subProgramId,
    updateAllocations: programRegistrationIds.map((regId, index)  => ({
      allocationId: regId,
      newRoomInventoryId: roomInventoryId,
      bedPosition: index + 1,
    })),
  };
  putCallWithLoader(endPoints?.updateAllocations, payload, PORTAL, textConstant.LARGE)
    .then((response) => {
      console.log("Room allocation updated successfully", response);
    })
    .catch((error) => {
      console.error("Error updating room allocation", error);
    })
    .finally(() => {
      if(offsetNumber === roomOffset){
        fetchRoomData && fetchRoomData(true);
      }
      else{
        setRoomOffset && setRoomOffset(offsetNumber || 0);
      }
      fetchApi && fetchApi(true);
    });
};

export const getOtherRoommateId = (rooms: unknown[], regId: number) => {
  for (const room of rooms) {
    for (const occupant of room.occupants) {
      if (occupant?.value?.roomAllocationId === regId) {
        return room?.occupants?.map(
          (item) => item?.value?.roomAllocationId,
        );
      }
    }
  }
  return null;
};

export const unallocateRoomForPair = (
  programRegistrationIds: Array<number>,
  programId?: string | number,
  subProgramId?: string | number | undefined,
  fetchRoomData?: (reload: boolean) => void,
  fetchApi?: (reload: boolean) => void,
  roomOffset?: number,
  setRoomOffset?: React.Dispatch<React.SetStateAction<number>>,
  offsetNumber?: number,
) => {
  deleteCallWithLoader(endPoints?.clearRoom, {
    programId: Number(programId),
    subProgramId: subProgramId,
    allocationIds: programRegistrationIds,
  },
  PORTAL,
  textConstant.LARGE
  )
    .then((response) => {
      console.log("Room allocation updated successfully", response);
    })
    .catch((error) => {
      console.error("Error updating room allocation", error);
    })
    .finally(() => {
      if(offsetNumber === roomOffset){
        fetchRoomData && fetchRoomData(true);
      }
      else{
        setRoomOffset && setRoomOffset(offsetNumber || 0);
      }
      fetchApi && fetchApi(true);
    });
};
export const formatHDBCount = (count: number | undefined): string => {
  return (count || 0).toString().padStart(2, "0");
};
export const parseRoomId = (roomId: string): number => {
  return parseInt(roomId, 10);
};