import React from "react";
import styles from "./index.module.scss";
import { textAlign } from "@mui/system";

// Generated by Copilot

interface ProgramPreferenceProps {
  value: any;
  onChange: (newValue: any) => void;
  preferences: {
    id: number;
    name: string;
    duration: string;
    dates: string;
  }[];
}

const ProgramPreference: React.FC<ProgramPreferenceProps> = ({
  value,
  onChange,
  preferences,
}) => {
  return (
    <div className={styles.dragdropcontainer}>
      <div className={styles.header}>
       
      </div>

      <div className={styles.content}>
        {/* Mahatria's Choice Section */}
        <div className={styles.mahatriaChoiceSection}>
          <div className={styles.mahatriaChoiceCard}>
            <div className={styles.checkbox}>
              <input type="checkbox" readOnly />
            </div>
            <div className={styles.choiceText}>
              I'm Comfortable with{" "}
              <span className={styles.highlight}>Mahatria's</span> Choice for My
              HDB Program selection
            </div>
          </div>
        </div>

        {/* Programs Grid */}
        <div className={styles.programsGrid}>
          {preferences.map((program, idx) => (
            <div key={program.id} className={styles.programItem}>
              <div className={styles.programHeader}>
                <div className={styles.programInfo}>
                  <div className={styles.programName}>{program.name}</div>
                  <div className={styles.programDatesSection}>
                    <div className={styles.programDuration}>
                      {program.duration}
                    </div>
                    <div className={styles.programDates}>{program.dates}</div>
                  </div>
                </div>
              </div>
              <div className={styles.priorityButtons}>
                {[1, 2, 3, 4, 5].map((priority) => (
                  <button
                    key={priority}
                    className={styles.priorityButton}
                    disabled={false}
                  >
                    Choice {priority}
                  </button>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
      <div className={styles.preferenceSummaryContainer}>
        <div className={styles.preferenceSummary}>
          <div className={styles.summaryText}>
            <span className={styles.text}>No preferences selected</span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ProgramPreference;
// Generated by Copilot
