import { getProgramKeys, pickUpTimings } from '../../../constants';
import styles from './index.module.scss';
import copy from '../../../assets/images/copy.webp';
import { useState } from 'react';
import { Question } from '../../../types/seatApproval';

// Generated by Copilot
const CustomCard = ({ content, cardContent, allocatedProgram, question }: { 
  content: string | null, 
  cardContent: any, 
  allocatedProgram: any, 
  question: Question,
}) => {
   const [copied, setCopied] = useState(false); // Add this state
   let cardContentValue = cardContent?.dialogueContent || "";
  if (allocatedProgram) {
    const programKey = getProgramKeys(cardContent.isShow + " " + question.bindingKey); 
    const timingValue = allocatedProgram[programKey];
    cardContentValue = pickUpTimings(timingValue, cardContent.isShow + " " + question.bindingKey, allocatedProgram);
   
  }
  if (!cardContentValue && content) {
    cardContentValue = content;
  }
  const MAP_URL = "https://www.google.com/maps/place/Ratnadeep+Super+Market+Pvt.+Ltd/@17.4431581,78.5046021,17z/data=!3m2!4b1!5s0x3bcb9a3a2f1ce7d7:0x5e32cb3005b8b83!4m6!3m5!1s0x3bcb9b972bfdba3d:0x276b387188e2c0e1!8m2!3d17.443153!4d78.507177!16s%2Fg%2F11ny51bn2h?entry=ttu&g_ep=EgoyMDI1MDgxNy4wIKXMDSoASAFQAw%3D%3D";
  const leonia = "https://maps.app.goo.gl/kU2zr2tGMG8Tsgvn9"

  const colonIdx = cardContentValue ? cardContentValue.indexOf(":") : -1;
  const renderContent = () => {
  // Helper function to bold day, date, month, year, and time in the text
  const formatDayAndTime = (text: string) => {
    // Combined pattern to match day names, dates, months, years, and times
    const pattern = /(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday|\d{1,2}\s+(?:January|February|March|April|May|June|July|August|September|October|November|December)|January|February|March|April|May|June|July|August|September|October|November|December|\b\d{4}\b|\d{1,2}:\d{2}\s*(?:a\.m\.|p\.m\.))/gi;
    
    const parts = text.split(pattern);
    
    return parts.map((part, i) => {
      if (pattern.test(part)) {
        return <b key={`bold-${i}`}>{part}</b>;
      }
      return part;
    });
  };

  if (cardContentValue && colonIdx !== -1) {
    return (
      <>
        <b>{cardContentValue.slice(0, colonIdx + 1)}</b>
        {formatDayAndTime(cardContentValue.slice(colonIdx + 1))}
        {
          (cardContent.isShow + " " + question.bindingKey == "own transport travelPlanOnward" || 
           cardContent.isShow + " " + question.bindingKey == "own transport travelPlanReturn") && 
          <p>
            <a href={leonia}>view on map</a>
            <span className={styles.imageContainer}>
              <img
                src={copy}
                className={styles.copyImage}
                alt="copy"
                onClick={() => {
                  navigator.clipboard.writeText(leonia);
                  setCopied(true);
                  setTimeout(() => setCopied(false), 400);
                }}
              />
              {copied && (
                <span className={styles.tooltipCopied}>Copied!</span>
              )}
            </span>
          </p>
        }
        {
          (cardContent.isShow + " " + question.bindingKey == "city pick up travelPlanOnward" || 
           cardContent.isShow + " " + question.bindingKey == "city drop travelPlanReturn") &&
          <p>
            <a href={MAP_URL}>view on map</a>
            <span className={styles.imageContainer}>
              <img
                src={copy}
                className={styles.copyImage}
                alt="copy"
                onClick={() => {
                  navigator.clipboard.writeText(MAP_URL);
                  setCopied(true);
                  setTimeout(() => setCopied(false), 400);
                }}
              />
              {copied && (
                <span className={styles.tooltipCopied}>Copied!</span>
              )}
            </span>
          </p>
        }
      </>
    );
  }
  return cardContentValue;
};
  return (
    <div className={styles.cardContainer}>
      <p className={styles.card_content}>
        {renderContent()}
      </p>
    </div>
  );
};

export default CustomCard;
